echo Executing NeXTTool to upload /usr/include/../../../../nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /cygdrive/C/cygwin/nexttool/NeXTTool.exe /COM=usb -firmware=/usr/include/../../../../nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
